{{ if .Values.jhubExtResAllocExporterEnabled }}

# Create a deployment for the exporter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-res-alloc-exporter
  namespace: {{ .Values.monitoringNamespace | default "monitoring" }}
  labels:
    app: ext-res-alloc-exporter
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: ext-res-alloc-exporter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: ext-res-alloc-exporter
        tier: service
    spec:
      serviceAccountName: ext-resource-exporter
      containers:
      - name: exporter
        image: {{ .Values.jhubCustomExporterImage }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "250m"

        ports:
        - containerPort: 8080

        command: ["python3", "/custom_exporters/gpu_alloc_exporter.py"]

        env:
          - name: PORT
            value: "8080"
          - name: MONITORED_NAMESPACES
            value: {{ .Values.jhubExtResAllocExporterNamespaces | toJson | squote }}
          - name: EXTENDED_RESOURCES
            value: {{ .Values.jhubExtResAllocExporterExtendedResources | toJson | squote }}
          - name: DEBUG
            value: {{ .Values.jhubExtResAllocExporterDebug | squote }}
          - name: NODE_LABEL_FOR_MODEL
            value: {{ .Values.jhubExtResAllocExporterNodeLabelForModel | squote }}



---

apiVersion: v1
kind: Service
metadata:
  name: ext-res-alloc-exporter
  namespace: {{ .Values.monitoringNamespace | default "monitoring" }}

  labels:
    app: ext-res-alloc-exporter
    tier: service

spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: ext-res-alloc-exporter
    

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ext-resource-exporter
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["nodes", "pods"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ext-resource-exporter
subjects:
  - kind: ServiceAccount
    name: ext-resource-exporter
    namespace: {{ .Values.monitoringNamespace | default "monitoring" }}
roleRef:
  kind: ClusterRole
  name: ext-resource-exporter
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ext-res-alloc-exporter
  name: ext-resource-exporter
  namespace: moni{{ .Values.monitoringNamespace | default "monitoring" }}toring


{{ end }}

