apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-monitor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-user-monitor
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-user-monitor
    spec:
      # serviceAccountName: {{ .Release.Name }}-usermonitor-account
      restartPolicy: Always
      volumes:
        - name: grafana-persistency
          nfs:
            server: {{ .Values.nfsServerAddress | required "nfsServerAddress requred" }}
            path: {{ .Values.grafanaNfsPath | required "grafanaNfsPath" }}
        - name: grafana-datasources
          secret:
            secretName: {{ .Release.Name }}-grafana-datasources

      containers:
        - name: database
          image: postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresPassword | required "postgresPassword cannot be empty" }}
        - name: grafana
          image: grafana/grafana-enterprise
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-persistency
              mountPath: /var/lib/grafana/
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: superuser
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafanaAdminPassword | required "grafanaAdminPassword cannot be empty" }}
            - name: GF_LOG_LEVEL
              value: debug
            - name: GF_SERVER_ROOT_URL
              value: 'https://{{ trimSuffix "/" .Values.hostname }}/grafana'
            - name: GF_SERVER_DOMAIN
              value: {{ .Values.grafanaServerDomain | required "grafanaServerDomain cannot be empty" }}
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN
              value: "false"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: {{ .Values.OAuthName | default "OAuth2" }}
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              value: {{ .Values.IamClientId | required "IamClientId must be set" }}
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              value: {{ .Values.IamClientSecret | required "IamClientSecret must be set" }}
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: {{ .Values.OAuthEndpoint }}/authorize
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: {{ .Values.OAuthEndpoint }}/token
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: {{ .Values.OAuthEndpoint }}/userinfo
            - name: GF_AUTH_GENERIC_OAUTH_USE_PKCE
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_USE_REFRESH_TOKEN
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: openid email profile
            - name: GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH
              value: email
            - name: GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH
              value: preferred_username
            - name: GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH
              value: full_name
            - name: GF_AUTH_GENERIC_OAUTH_ALLOWED_GROUPS
              value: {{ .Values.grafanaOAuthAllowedGroup }}
            - name: GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH
              value: groups

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-datasources
stringData:
  grafana-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: ephemeral-psql
        type: postgres
        url: localhost:5432
        user: postgres
        secureJsonData:
          password: {{ .Values.postgresPassword }}
        jsonData:
          sslmode: disable

      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-stack-kube-prom-prometheus:9090
        basicAuth: false
        jsonData:
          tlsSkipVerify: {{ .Values.tlsSkipVerify | default true }}
        isDefault: true

---

apiVersion: v1
kind: Service
metadata:
  name: user-monitor
  labels:
    app: {{ .Release.Name }}-user-monitor
spec:
  selector:
    app: {{ .Release.Name }}-user-monitor
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: psql
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: 
    cert-manager.io/cluster-issuer: lets-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: {{ .Release.Name }}-usermonitor
spec: 
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostname | required "hostname required" }}
    http:
      paths:
      - backend:
          service: 
            name: {{ .Release.Name }}-user-monitor
            port:
              name: http
        path: /grafana
        pathType: Prefix

