apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ .Release.Name }}-kube-eagle
spec:
  repo: https://raw.githubusercontent.com/cloudworkz/kube-eagle-helm-chart/master
  chart: kube-eagle
  targetNamespace: {{ .Release.Namespace }}
  createNamespace: true
  valuesContent: |-
    serviceMonitor:
      create: true
      releaseLabel: prometheus-stack


