
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-usermonitor-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-usermonitor-role
rules:
  - apiGroups: [kueue.x-k8s.io]
    resources: [workloads, "workloads/status"]
    verbs: [list, watch, patch, get]
  - apiGroups: [batch]
    resources: [jobs, "jobs/status"]
    verbs: [list, watch, patch, get]
  - apiGroups: [ "" ]
    resources: [pods, "pods/status", "pods/logs"]
    verbs: [list, watch, patch, get]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-usermonitor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-usermonitor-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-usermonitor-account


{{ if .Values.jhubExtResAllocExporterEnabled }}
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ext-resource-exporter
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["nodes", "pods"]
    verbs: ["get", "watch", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ext-resource-exporter
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-ext-resource-exporter
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-ext-resource-exporter
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Release.Name }}-ext-res-alloc-exporter
  name: {{ .Release.Name }}-ext-resource-exporter

{{ end }}
